language: python
python:
  - 2.7
  
notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

install:

# Setup anaconda
  - ldd --version
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - cd install/requirements/
  - ./requirements.sh
  - cd ../..

# FSL
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get install -qq --no-install-recommends fsl
  - travis_retry sudo apt-get install -qq fsl-atlases
  - source /etc/fsl/fsl.sh

# The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# SCT: set PATH
  - SCT_DIR="/home/travis/build/neuropoly/spinalcordtoolbox"
  - PATH=${PATH}:${SCT_DIR}/bin
  - PATH=${PATH}:${SCT_DIR}/bin/linux
  - export SCT_DIR PATH
  - . ~/.bashrc

# SCT: create links
  - ./install/create_links.sh -a

# Go to testing folder
  - cd testing

script:
  - python ../scripts/sct_check_dependences.py
  - python test_all.py -d 1
  - cd ../install
  - python create_package.py -s linux
  - cd ../spinalcordtoolbox_v*
  - python installer.py -p ~/
  - echo "DONE"
